dist: xenial
language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
before_install: composer config -g github-oauth.github.com "85e7fb6b9ee9ad4ff619e0c86a5ed076bd18a179"
install:
  - composer install
before_script: phpenv config-add .travis_config.ini
script: vendor/bin/phpunit --coverage-text
cache:
  directories:
    - $HOME/.composer/cache/files